name: Test EasyMergeR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permet d'exécuter manuellement

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # Remplace macOS par Ubuntu si besoin
    strategy:
      matrix:
        r-version: ['4.2.2']  # Choisir une version récente de R

    steps:
      - name: Checkout le dépôt
        uses: actions/checkout@v4

      - name: Installer R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Installer les dépendances R nécessaires
        run: |
          install.packages("devtools")
          install.packages(c("shiny", "tidyverse", "readxl", "writexl"))
        shell: Rscript {0}

      - name: Installer EasyMergeR depuis GitHub
        run: |
          devtools::install_git("https://github.com/ai4kids/EasyMergeR")
        shell: Rscript {0}

      - name: Tester EasyMergeR
        run: |
          library(EasyMergeR)
          print("EasyMergeR installé et fonctionnel !")
        shell: Rscript {0}
